[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && cd backend && pnpm exec prisma generate"

[deploy]
startCommand = "cd backend && pnpm exec ts-node-dev --transpile-only --no-notify src/main.ts"
restartPolicyType = "on_failure"
