[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "cd backend && npx ts-node --transpile-only --esm src/main.ts"
restartPolicyType = "on_failure"
